#!/usr/bin/env python
# Copyright 2006-2012 Mark Diekhans

import unittest, sys, os
from optparse import OptionParser
sys.path.append(".")
from pycbio.sys import fileOps,strOps

class CmdOpts(object):
    usage = """%prog

    run all tests
"""
    def __init__(self):
        parser = OptionParser(usage=CmdOpts.usage)
        (opts, args) = parser.parse_args()
        if len(args) != 0:
            parser.error("wrong number of arguments")


class DynTest(object):
    "dynamic loading and executing of test"
    def __init__(self):
        self.suites = []
        self.importErrCnt = 0
        self.pkgs = set()

    def add(self, name):
        "add a module, continuing past import error"
        pkgName, modName = name.rsplit(".", 1)
        self.pkgs.add(pkgName)
        try:
            mod = __import__(pkgName,  globals(), None, [modName])
            mod = getattr(mod, modName)
            self.suites.append(mod.suite())
        except ImportError, e:
            self.importErrCnt += 1
            sys.stderr.write("Error: import failed for: " + name + ": " + str(e) + "\n")

    bar = strOps.dup(70, "=") + "\n"

    def run(self):
        alltests = unittest.TestSuite(self.suites)
        runner = unittest.TextTestRunner(sys.stdout, verbosity=2)
        result = runner.run(alltests)
        sys.stdout.flush()
        sys.stderr.flush()
        sys.stderr.write(self.bar)
        if not (result.wasSuccessful() and (self.importErrCnt == 0)):
            sys.stderr.write("Error summary:\n")
            if self.importErrCnt > 0:
                sys.stderr.write("\timport errors: "+str(self.importErrCnt)+"\n")
            if len(result.failures) > 0:
                sys.stderr.write("\ttest failures: "+str(len(result.failures))+"\n")
            if len(result.errors) > 0:
                sys.stderr.write("\ttest errors: "+str(len(result.errors))+"\n")
            sys.exit(1)
        else:
            sys.stderr.write("Tests successful\n")

    def cleanup(self):
        "clean up output directories from all test packages"
        for pkg in self.pkgs:
            pkgOutDir = pkg.replace(".", "/") + "/output"
            if os.path.isdir(pkgOutDir):
                fileOps.rmTree(pkgOutDir)

dt = DynTest()
dt.add("pycbio.tsv.tests.TSVTests")
dt.add("pycbio.tsv.tests.TabFileTests")
dt.add("pycbio.sys.tests.EnumerationTests")
dt.add("pycbio.sys.tests.ImmutableTests")
dt.add("pycbio.sys.tests.ExceptTests")
dt.add("pycbio.sys.tests.ProcDagTests")
dt.add("pycbio.sys.tests.PipelineTests")
dt.add("pycbio.sys.tests.ProcOpsTests")
dt.add("pycbio.sys.tests.ColorTests")
dt.add("pycbio.sys.tests.DbDictTests")
dt.add("pycbio.hgdata.tests.GenePredTests")
dt.add("pycbio.hgdata.tests.GeneCheckTests")
dt.add("pycbio.hgdata.tests.PslTests")
dt.add("pycbio.hgdata.tests.PslDbTests")
dt.add("pycbio.hgdata.tests.PslMapTests")
dt.add("pycbio.hgdata.tests.ClusterGenesTests")
#FIXME: dt.add("pycbio.stats.tests.HistoTests")
dt.add("pycbio.stats.tests.SubsetsTests")
dt.add("pycbio.stats.tests.VennTests")
dt.add("pycbio.exrun.tests.BasicTests")
dt.add("pycbio.exrun.tests.ErrorTests")
dt.add("pycbio.exrun.tests.SchedTests")
dt.add("pycbio.exrun.tests.BigTests")
dt.add("pycbio.exrun.tests.CmdTests")
dt.add("pycbio.exrun.tests.BigTests")
dt.add("pycbio.align.tests.PairAlignTest")
dt.add("pycbio.hgbrowser.tests.BrowserDirTests")
dt.run()

opts = CmdOpts()
dt.cleanup()
