#!/usr/bin/env python
# Copyright 2006-2011 Mark Diekhans

import sys, os
myBinDir = os.path.normpath(os.path.dirname(sys.argv[0]))
sys.path.append(myBinDir + "/../lib")
from optparse import OptionParser
from pycbio.hgdata.ClusterGenes import ClusterGenes
from pycbio.sys.fileOps import prRow, prRowv, readFileLines

class CmdOpts(object):
    usage="""%prog [options] clusterFile outFile

    Select clusters based on the criteria specified by the options.
    By default, output a clusterGenes file with just the selected
    records.  If multiple select criteria are specified, they all
    must be true to select the loci.

    Somes options take track sets, which are comma seperated sets
    of track names.
"""

    def __init__(self):
        parser = OptionParser(usage=CmdOpts.usage)
        parser.add_option("--trackSet",
                          action="append", dest="trackSet", default=None,
                          help="""selects loci that have at least the specified set of tracks.
                                  Maybe specified multiple times.""")
        parser.add_option("--notTrackSet",
                          action="append", dest="notTrackSet", default=None,
                          help="""selects loci that don't have any of the specified set of tracks.
                                  Maybe specified multiple times.""")
        parser.add_option("--onlyTrackSet",
                          action="append", dest="onlyTrackSet", default=None,
                          help="""This selects loci that only the specified set of tracks.
                                  Maybe specified multiple times.""")
        parser.add_option("--notOnlyTrackSet",
                          action="append", dest="notOnlyTrackSet", default=None,
                          help="""This selects loci that don't have only the specified set of tracks.
                                  Maybe specified multiple times.""")
        parser.add_option("--geneIds", action="append", dest="geneIdFiles", default=None,
                          help="""select loci containing these gene ids""")
        parser.add_option("--trackFilter", action="store", dest="trackFilterSet", default=None,
                          help="""Only output tracks in this set.  Loci that don't contain any of these tracks are dropped""")
        parser.add_option("--clusterBedOutput", action="store_true", dest="clusterBedOutput", default=False,
                          help="""Output loci bed for select loci""")
        (opts, args) = parser.parse_args()
        if len(args) != 2:
            parser.error("wrong number of arguments")
        (self.clusterFile, self.outFile) = args
        self.__dict__.update(opts.__dict__)
            

class ClusterSelect(object):
    def __init__(self, opts):
        self.clusters = ClusterGenes(opts.clusterFile)

        self.trackSets = self.__parseTrackSetList(opts.trackSet) if (opts.trackSet != None) else None
        self.notTrackSets = self.__parseTrackSetList(opts.notTrackSet) if (opts.notTrackSet != None) else None
        self.onlyTrackSets = self.__parseTrackSetList(opts.onlyTrackSet) if (opts.onlyTrackSet != None) else None
        self.notOnlyTrackSets = self.__parseTrackSetList(opts.notOnlyTrackSet) if (opts.notOnlyTrackSet != None) else None
        self.geneIds = self.__loadIdFiles(opts.geneIdFiles) if (opts.geneIdFiles != None) else None
        self.trackFilterSet = self.__parseTrackSet(opts.trackFilterSet) if (opts.trackFilterSet != None) else None

    def __parseTrackSet(self, spec):
        selSet = set()
        for tr in spec.split(","):
            selSet.add(intern(tr))
        return selSet

    def __parseTrackSetList(self, specs):
        trackSetList = []
        for spec in specs:
            trackSetList.append(self.__parseTrackSet(spec))
        return trackSetList

    def __loadIdFiles(self, idFiles):
        ids = set()
        for f in idFiles:
            for line in readFileLines(f):
                ids.add(line.strip())
        return ids

    def __selectedByTrackSets(self, cl):
        for ts in self.trackSets:
            if ts & cl.tableSet:
                return True
        return False

    def __rejectedByNotTrackSets(self, cl):
        for ts in self.notTrackSets:
            if ts & cl.tableSet:
                return True
        return False

    def __selectedByOnlyTrackSets(self, cl):
        for ts in self.onlyTrackSets:
            if ts == cl.tableSet:
                return True
        return False

    def __rejectedByNotOnlyTrackSets(self, cl):
        for ts in self.notOnlyTrackSets:
            if ts == cl.tableSet:
                return True
        return False

    def __selectedByGeneId(self, cl):
        for gene in cl:
            if gene.gene in self.geneIds:
                return True
        return False

    def __selected(self, cl):
        if (self.trackSets != None) and not self.__selectedByTrackSets(cl):
            return False
        if (self.notTrackSets != None) and self.__rejectedByNotTrackSets(cl):
            return False
        if (self.onlyTrackSets != None) and not self.__selectedByOnlyTrackSets(cl):
            return False
        if (self.notOnlyTrackSets != None) and self.__rejectedByNotOnlyTrackSets(cl):
            return False
        if (self.geneIds != None) and not self.__selectedByGeneId(cl):
            return False
        if (self.trackFilterSet != None) and not (self.trackFilterSet & cl.tableSet):
            return False
        return True

    def outClusters(self, outFile):
        outFh = open(outFile, "w")
        outFh.write('#')
        prRow(outFh, self.clusters.columns)
        
        for cl in self.clusters:
            if self.__selected(cl):
                cl.write(outFh, self.trackFilterSet)
        outFh.close()

    def __writeClusterBed(self, outFh, cl):
        prRowv(outFh, cl.chrom, cl.start, cl.end, cl.clusterId, 0, cl.strand)

    def outClusterBed(self, outFile):
        outFh = open(outFile, "w")
        for cl in self.clusters:
            if self.__selected(cl):
                self.__writeClusterBed(outFh, cl)
        outFh.close()

opts = CmdOpts()
clSelect = ClusterSelect(opts)
if opts.clusterBedOutput:
    clSelect.outClusterBed(opts.outFile)
else:
    clSelect.outClusters(opts.outFile)
