* nasty BUG:  calling pipeline in a loop agaisnt an open file truncates it each exec
    ouch, this happens with subprocess.call_check too
    does this happen in pipettor?

* drop RDB support in TSV
* document generators:
  http://codespeak.net/~mwh/pydoctor/ - discussion of others

* rename pycbio.sys, it prevent moving PycbioException up one level, since PycbioException imports
  standard sys. Specifying absolute import still breaks pipeline because pickle of exceptions doesn't
  work.

* reverse asserts so order is expect, got (corresponds to diff outout, see pslMapTests)

* add function to init from __init__ args
  http://code.activestate.com/recipes/286185-automatically-initializing-instance-variables-from/
* switch all function to use coords
* exceptTests has to hack around unit test _AssertRaisesContext not saving traceback
see unittest/case.py: # store exception, without traceback, for later retrieval

* convert lib/pycbio/hgdata/binnerSA.py to peewee
* GenePred, etc should have abstraction around from dbColIdxMap, could be good
switch to dictcursors
* also custom cursors that work off of namedtuples would be great, especially to unify the sqlite/mysql interface stuff.
* tests use obsolete makeSuite
